baseURL = "https://pragmatech.digital/"
languageCode = "en-us"
title = "Engineering Confidence | PragmaTech"
theme = "pragmatech-theme"

[params]
description = "Enabling Java Developers to Frequently Deliver Software with More Confidence"
matomoURL = "https://analytics.pragmatech.de/"
matomoSiteID = "1"

[Params]
  description = "Enabling Developers to Frequently Deliver Software with More Confidence."
  logo = "images/pragmatech-banner.png"
  images = ["images/pragmatech-banner.png"]
  title = "PragmaTech GmbH"
  favicon = true

[Params.social]
  linkedin = "https://www.linkedin.com/company/pragmatech-digital-solutions/"
  twitter = "https://twitter.com/pragmatechds"
  github = "https://github.com/PragmaTech-Digital-Solutions"
  instagram = "https://www.instagram.com/pragmatech.ds"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
