baseURL = "https://pragmatech.de/"
languageCode = "en-us"
title = "PragmaTech - Confident Software Delivery"
theme = "pragmatech-theme"

[params]
description = "Enabling Java Developers to Frequently Deliver Software with More Confidence"
matomoURL = "https://analytics.pragmatech.de/"
matomoSiteID = "1"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Consulting"
url = "/consulting"
weight = 2
[[menu.main]]
name = "Workshops"
url = "/workshops"
weight = 3
[[menu.main]]
name = "Books"
url = "/books"
weight = 4
[[menu.main]]
name = "Courses"
url = "/courses"
weight = 5
[[menu.main]]
name = "About"
url = "/about"
weight = 6
[[menu.main]]
name = "Newsletter"
url = "/newsletter"
weight = 7
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 8
