## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
# baseURL = "/"
publishDir = "public"

# Remote
baseURL = "https://pragmatech.digital/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]

[Params.asset]
